[2024-06-16T18:40:03.379+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T13:05:29.173999+00:00/task_id=transform_mumbai_weather_data permission to 509
[2024-06-16T18:40:03.623+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T13:05:29.173999+00:00/task_id=transform_mumbai_weather_data permission to 509
[2024-06-16T18:40:03.650+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_etl.transform_mumbai_weather_data manual__2024-06-16T13:05:29.173999+00:00 [queued]>
[2024-06-16T18:40:03.664+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_etl.transform_mumbai_weather_data manual__2024-06-16T13:05:29.173999+00:00 [queued]>
[2024-06-16T18:40:03.666+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-06-16T18:40:03.799+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_mumbai_weather_data> on 2024-06-16 13:05:29.173999+00:00
[2024-06-16T18:40:03.806+0530] {standard_task_runner.py:60} INFO - Started process 2529 to run task
[2024-06-16T18:40:03.811+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_etl', 'transform_mumbai_weather_data', 'manual__2024-06-16T13:05:29.173999+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_etl.py', '--cfg-path', '/tmp/tmpefd7afdx']
[2024-06-16T18:40:03.815+0530] {standard_task_runner.py:88} INFO - Job 51: Subtask transform_mumbai_weather_data
[2024-06-16T18:40:04.024+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T13:05:29.173999+00:00/task_id=transform_mumbai_weather_data permission to 509
[2024-06-16T18:40:04.027+0530] {task_command.py:423} INFO - Running <TaskInstance: weather_dag_etl.transform_mumbai_weather_data manual__2024-06-16T13:05:29.173999+00:00 [running]> on host DESKTOP-ATOQU9B.localdomain
[2024-06-16T18:40:04.368+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='email@udit.com' AIRFLOW_CTX_DAG_OWNER='udit' AIRFLOW_CTX_DAG_ID='weather_dag_etl' AIRFLOW_CTX_TASK_ID='transform_mumbai_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T13:05:29.173999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T13:05:29.173999+00:00'
[2024-06-16T18:40:04.370+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_data() missing 1 required positional argument: 'city_name'
[2024-06-16T18:40:04.397+0530] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_etl, task_id=transform_mumbai_weather_data, execution_date=20240616T130529, start_date=20240616T131003, end_date=20240616T131004
[2024-06-16T18:40:04.519+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task transform_mumbai_weather_data (transform_data() missing 1 required positional argument: 'city_name'; 2529)
[2024-06-16T18:40:04.549+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-16T18:40:04.580+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
