[2024-06-16T18:41:00.923+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T13:05:29.173999+00:00/task_id=transform_hyderabad_weather_data permission to 509
[2024-06-16T18:41:01.177+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T13:05:29.173999+00:00/task_id=transform_hyderabad_weather_data permission to 509
[2024-06-16T18:41:01.207+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_etl.transform_hyderabad_weather_data manual__2024-06-16T13:05:29.173999+00:00 [queued]>
[2024-06-16T18:41:01.233+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_etl.transform_hyderabad_weather_data manual__2024-06-16T13:05:29.173999+00:00 [queued]>
[2024-06-16T18:41:01.237+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-06-16T18:41:01.379+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_hyderabad_weather_data> on 2024-06-16 13:05:29.173999+00:00
[2024-06-16T18:41:01.387+0530] {standard_task_runner.py:60} INFO - Started process 2549 to run task
[2024-06-16T18:41:01.392+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_etl', 'transform_hyderabad_weather_data', 'manual__2024-06-16T13:05:29.173999+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_etl.py', '--cfg-path', '/tmp/tmp_yjfuhwl']
[2024-06-16T18:41:01.397+0530] {standard_task_runner.py:88} INFO - Job 53: Subtask transform_hyderabad_weather_data
[2024-06-16T18:41:01.602+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T13:05:29.173999+00:00/task_id=transform_hyderabad_weather_data permission to 509
[2024-06-16T18:41:01.604+0530] {task_command.py:423} INFO - Running <TaskInstance: weather_dag_etl.transform_hyderabad_weather_data manual__2024-06-16T13:05:29.173999+00:00 [running]> on host DESKTOP-ATOQU9B.localdomain
[2024-06-16T18:41:01.937+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='email@udit.com' AIRFLOW_CTX_DAG_OWNER='udit' AIRFLOW_CTX_DAG_ID='weather_dag_etl' AIRFLOW_CTX_TASK_ID='transform_hyderabad_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T13:05:29.173999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T13:05:29.173999+00:00'
[2024-06-16T18:41:01.942+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_data() missing 1 required positional argument: 'city_name'
[2024-06-16T18:41:01.966+0530] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_etl, task_id=transform_hyderabad_weather_data, execution_date=20240616T130529, start_date=20240616T131101, end_date=20240616T131101
[2024-06-16T18:41:02.103+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task transform_hyderabad_weather_data (transform_data() missing 1 required positional argument: 'city_name'; 2549)
[2024-06-16T18:41:02.131+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-16T18:41:02.160+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
