[2024-06-16T20:04:56.844+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T14:23:36.799712+00:00/task_id=load_to_s3_bucket permission to 509
[2024-06-16T20:04:57.220+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T14:23:36.799712+00:00/task_id=load_to_s3_bucket permission to 509
[2024-06-16T20:04:57.254+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_etl.load_to_s3_bucket manual__2024-06-16T14:23:36.799712+00:00 [queued]>
[2024-06-16T20:04:57.273+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_etl.load_to_s3_bucket manual__2024-06-16T14:23:36.799712+00:00 [queued]>
[2024-06-16T20:04:57.276+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-06-16T20:04:57.439+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_s3_bucket> on 2024-06-16 14:23:36.799712+00:00
[2024-06-16T20:04:57.447+0530] {standard_task_runner.py:60} INFO - Started process 6003 to run task
[2024-06-16T20:04:57.453+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_etl', 'load_to_s3_bucket', 'manual__2024-06-16T14:23:36.799712+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_etl.py', '--cfg-path', '/tmp/tmpcb_sw1qd']
[2024-06-16T20:04:57.457+0530] {standard_task_runner.py:88} INFO - Job 100: Subtask load_to_s3_bucket
[2024-06-16T20:04:57.636+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T14:23:36.799712+00:00/task_id=load_to_s3_bucket permission to 509
[2024-06-16T20:04:57.640+0530] {task_command.py:423} INFO - Running <TaskInstance: weather_dag_etl.load_to_s3_bucket manual__2024-06-16T14:23:36.799712+00:00 [running]> on host DESKTOP-ATOQU9B.localdomain
[2024-06-16T20:04:58.045+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='email@udit.com' AIRFLOW_CTX_DAG_OWNER='udit' AIRFLOW_CTX_DAG_ID='weather_dag_etl' AIRFLOW_CTX_TASK_ID='load_to_s3_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T14:23:36.799712+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T14:23:36.799712+00:00'
[2024-06-16T20:05:19.421+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/d/Programs/weather etl/dags/weather_dag_etl.py", line 60, in load_data_to_s3_bucket
    for filename in os.listdir("../weather_data/"):
FileNotFoundError: [Errno 2] No such file or directory: '../weather_data/'
[2024-06-16T20:05:19.445+0530] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_etl, task_id=load_to_s3_bucket, execution_date=20240616T142336, start_date=20240616T143457, end_date=20240616T143519
[2024-06-16T20:05:19.620+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task load_to_s3_bucket ([Errno 2] No such file or directory: '../weather_data/'; 6003)
[2024-06-16T20:05:19.655+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-16T20:05:19.684+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
