[2024-06-16T17:30:08.585+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T11:55:29.369171+00:00/task_id=transform_load_weather_data permission to 509
[2024-06-16T17:30:09.373+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T11:55:29.369171+00:00/task_id=transform_load_weather_data permission to 509
[2024-06-16T17:30:09.414+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_etl.transform_load_weather_data manual__2024-06-16T11:55:29.369171+00:00 [queued]>
[2024-06-16T17:30:09.449+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_etl.transform_load_weather_data manual__2024-06-16T11:55:29.369171+00:00 [queued]>
[2024-06-16T17:30:09.451+0530] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-06-16T17:30:09.572+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-06-16 11:55:29.369171+00:00
[2024-06-16T17:30:09.586+0530] {standard_task_runner.py:60} INFO - Started process 1017 to run task
[2024-06-16T17:30:09.602+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_etl', 'transform_load_weather_data', 'manual__2024-06-16T11:55:29.369171+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_etl.py', '--cfg-path', '/tmp/tmpd4rw1fu9']
[2024-06-16T17:30:09.607+0530] {standard_task_runner.py:88} INFO - Job 23: Subtask transform_load_weather_data
[2024-06-16T17:30:09.797+0530] {logging_mixin.py:188} INFO - Changing /mnt/d/Programs/weather etl/logs/dag_id=weather_dag_etl/run_id=manual__2024-06-16T11:55:29.369171+00:00/task_id=transform_load_weather_data permission to 509
[2024-06-16T17:30:09.799+0530] {task_command.py:423} INFO - Running <TaskInstance: weather_dag_etl.transform_load_weather_data manual__2024-06-16T11:55:29.369171+00:00 [running]> on host DESKTOP-ATOQU9B.localdomain
[2024-06-16T17:30:10.008+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='email@udit.com' AIRFLOW_CTX_DAG_OWNER='udit' AIRFLOW_CTX_DAG_ID='weather_dag_etl' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T11:55:29.369171+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T11:55:29.369171+00:00'
[2024-06-16T17:30:10.022+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programs/weather etl/airflow-venv/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/d/Programs/weather etl/dags/weather_dag_etl.py", line 27, in transform_load_data
    time_of_record = data['dt'] + tz
TypeError: unsupported operand type(s) for +: 'int' and 'datetime.timezone'
[2024-06-16T17:30:10.045+0530] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_etl, task_id=transform_load_weather_data, execution_date=20240616T115529, start_date=20240616T120009, end_date=20240616T120010
[2024-06-16T17:30:10.450+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task transform_load_weather_data (unsupported operand type(s) for +: 'int' and 'datetime.timezone'; 1017)
[2024-06-16T17:30:10.462+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-16T17:30:10.497+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
